openapi: 3.0.3
info:
  title: Huemanely API
  version: "0.1.0"
  description: "HTTP API for Huemanely"
servers:
  - url: http://localhost:8080
components:
  schemas:
    Tenant:
      type: object
      properties:
        id:
          type: integer
        uuid:
          type: string
        name:
          type: string
        slug:
          type: string
        domain:
          type: string
          nullable: true
paths:
  /api/tenants:
    get:
      summary: List tenants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tenant'